name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  webAppPackagePath: './published'
  webAppName: 'FabLabSandbox' #name of azure webapp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ${{ env.webAppPackagePath }}
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webAppName }}
        publish-profile: ${{ secrets.PUBLISHSETTINGS }}
        package: ${{ env.webAppPackagePath }}
